### ISSUE TITLE
GA1DArrayGenome.C:225:3: error: use of undeclared identifier 'initializer'  initializer

### ISSUE THREAD

**Issue by liugoanywhere** [B0RJA/GAlib-mpi#1]
https://github.com/hoehrmann/pngwolf/issues/6‎
Error:
GA1DArrayGenome.C:225:3: error: use of undeclared identifier 'initializer'  initializer(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_INITIALIZER);
Same issue here. I was able to compile with clang on OS 10.9 by following a tip found at http://clang.debian.net/status.php?version=3.3&key=USE_OF_UNDECLARED_IDENTIFIER

Solution:
Update the following files files:

galib/ga/GA1DArrayGenome.C
galib/ga/GA2DArrayGenome.C
galib/ga/GA3DArrayGenome.C
Any instance of:

initializer(…);
mutator(…);
comparator(…);
crossover(…);
Replace with:

this->initializer(…);
this->mutator(…);
this->comparator(…);
this->crossover(…);
We should probably add to / write another patch file (the sevenzip920 patch didn't work for me, so I had to apply those changes manually as well – I believe the line numbers were wrong).

**Comment by B0RJA** [comment]
Thank you. I will fix the error.

Now I work with GAUL lib wich supports mpi and openmp.

Compilation instructions:  https://gist.github.com/B0RJA/9189165

**Comment by liugoanywhere** [comment]
Thank you. Jesus I thought U might be already away from keyboard cuz it has been not updated for long, and I should maintain it myself.
I find some other small issues and post on git.
